// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOeOD9gUTnxSlLVJW5vy6cfiS082n9bP8',
    appId: '1:792322125080:web:1c921cf3bb78795ccec26d',
    messagingSenderId: '792322125080',
    projectId: 'sign-language-app-2ee71',
    authDomain: 'sign-language-app-2ee71.firebaseapp.com',
    storageBucket: 'sign-language-app-2ee71.firebasestorage.app',
    measurementId: 'G-Y80410KERR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxCgvst7yHl1ApEB4JHn5uF8dTDBXcY6A',
    appId: '1:792322125080:android:f84364164527fedacec26d',
    messagingSenderId: '792322125080',
    projectId: 'sign-language-app-2ee71',
    storageBucket: 'sign-language-app-2ee71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCy41Bf5yWgRHj2tqmto2crqvaJeO3lO8',
    appId: '1:792322125080:ios:bc9bd89e835b8dd0cec26d',
    messagingSenderId: '792322125080',
    projectId: 'sign-language-app-2ee71',
    storageBucket: 'sign-language-app-2ee71.firebasestorage.app',
    iosBundleId: 'com.example.signLangugeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCy41Bf5yWgRHj2tqmto2crqvaJeO3lO8',
    appId: '1:792322125080:ios:bc9bd89e835b8dd0cec26d',
    messagingSenderId: '792322125080',
    projectId: 'sign-language-app-2ee71',
    storageBucket: 'sign-language-app-2ee71.firebasestorage.app',
    iosBundleId: 'com.example.signLangugeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOeOD9gUTnxSlLVJW5vy6cfiS082n9bP8',
    appId: '1:792322125080:web:5c42e2b59b980ee5cec26d',
    messagingSenderId: '792322125080',
    projectId: 'sign-language-app-2ee71',
    authDomain: 'sign-language-app-2ee71.firebaseapp.com',
    storageBucket: 'sign-language-app-2ee71.firebasestorage.app',
    measurementId: 'G-TP807715BT',
  );
}
